services:
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_storage:/qdrant/storage
        environment:
            - QDRANT_TELEMETRY_DISABLED=true
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    qdrant_storage:
